### PR TITLE
GH-13: Made the language client class configurable in the launchers.

### LINKED ISSUE #13: [enhancement] As an extension developer I would like to use a customized client instead of `LanguageClient` as my remote proxy
https://github.com/eclipse/sprotty-server/blob/f01d5a72f72ff0a0d698ecfe5c97ed6eaa5ab8d9/org.eclipse.sprotty.xtext/src/main/java/org/eclipse/sprotty/xtext/launch/DiagramServerSocketLauncher.xtend#L50

https://github.com/eclipse/sprotty-server/blob/f01d5a72f72ff0a0d698ecfe5c97ed6eaa5ab8d9/org.eclipse.sprotty.xtext/src/main/java/org/eclipse/sprotty/xtext/launch/DiagramServerLauncher.xtend#L71

Otherwise, I cannot send a push notification from the server to the client.

### PR DESCRIPTION
**Pull request by kittaakos**
Closes #13.

Signed-off-by: Akos Kitta <kittaakos@typefox.io>

### CODE REVIEW

**Comment by spoenemann** [comment]
LSP4J also allows to declare multiple remote service interface, which can be useful in case your extension does not inherit from LanguageClient. While we're at it, should we also support that, or do you think that's unnecessary?

**Comment by kittaakos** [comment]
> should we also support that, or do you think that's unnecessary?

I would cover it when we have the use-case.

> While we're at it

What somewhat bugs me is why did I have to change the code at two different places? Perhaps we can extract the common code within this PR. What do you think?

**Comment by spoenemann** [comment]
> What somewhat bugs me is why did I have to change the code at two different places? Perhaps we can extract the common code within this PR. What do you think?

If you have an idea for doing it, sure!

**Comment by kittaakos** [comment]
I have updated the PR and exposed the client class in the server setup so both launchers can use it.

Out of curiosity; should I avoid "fixing" the whitespaces in the future or not? I can revert the whitespace changes for this PR too.

**Comment by JanKoehnlein** [comment]
Thanks for the patch, @kittaakos.

In this repo we don't care that much about whitespace. Editing Xtend files in Eclipse usually adds the TABS to empty lines, and formatting would remove them.

**Pull request merged**
